### LOGIN
GET http://localhost:8000/api/mes-clients
Content-Type: application/json
Authorization:  Bearer 5|oTH6l1KRoMkRMtaVvoPAjqDT3tvuHUSbLPhtqpWc74a2d5b9

{
  "email": "revendeur@gmail.com",
  "password": "12345678"
}