### LOGIN
GET http://localhost:8000/api/clients
Content-Type: application/json
Authorization:  Bearer 2|gEVI6NRjyAAkxNlX2tKl0WRbYAA7slOQrmSABocA073037e1

{
  "email": "admin@example.com",
  "password": "password"
}